spring:
  application:
    # 应用名称,用于与其他应用进行区分
    name: start-exception-notifications
  profiles:
    active: test,throwException
  mail:
    # 邮箱服务器地址,如QQ邮箱的为 smtp.qq.com,阿里云企业邮箱的为 smtp.qiye.aliyun.com
    host: smtp.example.com
    # 发件人帐号
    username: example@example.com
    # 发件人密码
    password: example
    # 邮箱服务器端口
    port: 465
    # 邮件协议
    protocol: smtp
    # 默认字符编码
    default-encoding: UTF-8
    # 测试配置可用性
    test-connection: true
    # 如果使用加密端口需要添加下面的配置,否则不需要
    properties:
      mail.smtp.ssl.enable: true

# 接收异常信息的收件人帐号
x-start-exception:
  mail:
    to: example@example.com